gpw/gpw/Models/thanh_vien.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gpw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thanh_vien
    {
        public long id { get; set; }
        public string ho_ten { get; set; }
        public string dia_chi { get; set; }
        public string so_cmt { get; set; }
        public string nghe_nghiep { get; set; }
        public string hoc_van { get; set; }
        public string hinh_anh { get; set; }
        public string biet_danh { get; set; }
        public Nullable<int> doi_thu { get; set; }
        public string gioi_tinh { get; set; }
        public Nullable<System.DateTime> ngay_sinh { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public Nullable<int> trang_thai { get; set; }
        public Nullable<int> quyen_han { get; set; }
        public Nullable<double> lon { get; set; }
        public Nullable<double> lat { get; set; }
        public string cq_ctac { get; set; }
        public string email { get; set; }
        public string pass { get; set; }
        public string trinh_do { get; set; }
        public string so_dien_thoai { get; set; }
    }
}

gpw/gpw/Controllers/ThanhVienController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using gpw.Models;
using gpw.helpers;
using System.IO;
using Newtonsoft.Json;
using PagedList;
using PagedList.Mvc;

namespace gpw.Controllers
{
    public class ThanhVienController : Controller
    {
        private gpwEntities db = new gpwEntities();

        // GET: ThanhVien
        public ActionResult Index()
        {
            return View(db.thanh_vien.ToList());
        }

        // GET: ThanhVien/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            thanh_vien thanh_vien = db.thanh_vien.Find(id);
            if (thanh_vien == null)
            {
                return HttpNotFound();
            }
            return View(thanh_vien);
        }

        // GET: ThanhVien/Create
        public ActionResult Create()
        {
            if (configs.getCookie("thanhvien_id") != "") return RedirectToAction("Details", new { id = configs.getCookie("thanhvien_id") });
            ViewBag.TrinhDo = new List<SelectListItem>() { 
                new SelectListItem() { Value = "Đại học", Text = "Đại học" },
                new SelectListItem() { Value = "Cao đẳng", Text = "Cao đẳng" },
                new SelectListItem() { Value = "Trung cấp chuyên nghiệp", Text = "Trung cấp chuyên nghiệp" },
                new SelectListItem() { Value = "Trung học phổ thông", Text = "Trung học phổ thông" },
                new SelectListItem() { Value = "Trung học cơ sở", Text = "Trung học cơ sở" },
                new SelectListItem() { Value = "Tiểu học", Text = "Tiểu học" }
            };
            return View();
        }

        public ActionResult CheckEmailExist(string email)
        {
            string result = "0";
            if (email == null) email = "";
            var email1 = db.thanh_vien.Any(x => x.email == email);
            if (email1 == true)
            {
                result = "1";
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        // POST: ThanhVien/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(thanh_vien_model model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Vui lòng kiểm tra lại các trường.");
                return View(model);
            }
            try
            {
                thanh_vien _addNew = new thanh_vien();
                _addNew.ho_ten = model.ho_ten ?? null;
                _addNew.dia_chi = model.dia_chi ?? null;
                _addNew.lon = model.lon ?? null;
                _addNew.lat = model.lat ?? null;
                _addNew.so_cmt = model.so_cmt ?? null;
                _addNew.nghe_nghiep = model.nghe_nghiep ?? null;
                _addNew.hoc_van = model.hoc_van ?? null;
                _addNew.hinh_anh = model.hinh_anh ?? null;
                _addNew.biet_danh = model.biet_danh ?? null;
                _addNew.gioi_tinh = model.gioi_tinh ?? null;
                string dateTime = model.ngay_sinh != null ? model.ngay_sinh : null;
                DateTime? dt = new DateTime();
                if (dateTime != null)
                {
                    dt = Convert.ToDateTime(dateTime);
                }
                _addNew.ngay_sinh = model.ngay_sinh != null ? dt : null;
                _addNew.ngay_tao = DateTime.Now;
                _addNew.cq_ctac = model.cq_ctac ?? null;
                _addNew.email = model.email ?? null;
                var passHash = model.pass != null ? configs.Encrypt(model.pass) : null;
                _addNew.pass = passHash;
                _addNew.trinh_do = model.trinh_do ?? null;
                _addNew.so_dien_thoai = model.so_dien_thoai ?? null;
                db.thanh_vien.Add(_addNew);
                db.SaveChanges();
                // set cookie đăng nhập 
                configs.setCookie("thanhvien_id", _addNew.id.ToString());
                configs.setCookie("ten_thanh_vien", _addNew.ho_ten);

                return RedirectToAction("TaoGiaPha", new { id = _addNew.id });
            }
            catch (Exception ex)
            {
                configs.SaveTolog(ex.ToString());
                ModelState.AddModelError("", "Vui lòng kiểm tra lại các trường.");
                return View(model);
            }
        }

        public ActionResult DangXuat()
        {
            configs.RemoveCookie("thanhvien_id");
            configs.RemoveCookie("ten_thanh_vien");
            return RedirectToAction("Index", "Home");
        }

        // GET: ThanhVien/Edit/5
        public ActionResult Edit(long? id)
        {
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            ViewBag.TrinhDo = new List<SelectListItem>() { 
                new SelectListItem() { Value = "Đại học", Text = "Đại học" },
                new SelectListItem() { Value = "Cao đẳng", Text = "Cao đẳng" },
                new SelectListItem() { Value = "Trung cấp chuyên nghiệp", Text = "Trung cấp chuyên nghiệp" },
                new SelectListItem() { Value = "Trung học phổ thông", Text = "Trung học phổ thông" },
                new SelectListItem() { Value = "Trung học cơ sở", Text = "Trung học cơ sở" },
                new SelectListItem() { Value = "Tiểu học", Text = "Tiểu học" }
            };

            thanh_vien thanh_vien = db.thanh_vien.Find(id);
            if (thanh_vien == null)
            {
                return HttpNotFound();
            }
            var thanhvien = new thanh_vien_model()
            {
                id = thanh_vien.id,
                biet_danh = thanh_vien.biet_danh,
                cq_ctac = thanh_vien.cq_ctac,
                dia_chi = thanh_vien.dia_chi,
                email = thanh_vien.email,
                gioi_tinh = thanh_vien.gioi_tinh,
                hinh_anh = thanh_vien.hinh_anh,
                ho_ten = thanh_vien.ho_ten,
                hoc_van = thanh_vien.hoc_van,
                lat = thanh_vien.lat,
                lon = thanh_vien.lon,
                ngay_sinh = string.Format("{0:MM/dd/yyyy}", thanh_vien.ngay_sinh),
                nghe_nghiep = thanh_vien.nghe_nghiep,
                so_cmt = thanh_vien.so_cmt,
                so_dien_thoai = thanh_vien.so_dien_thoai,
                trinh_do = thanh_vien.trinh_do
            };
            return View(thanhvien);
        }

        // POST: ThanhVien/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "id,ho_ten,dia_chi,so_cmt,nghe_nghiep,hoc_van,hinh_anh,biet_danh,doi_thu,gioi_tinh,ngay_sinh,ngay_tao,trang_thai,quyen_han,lon,lat,cq_ctac,email,pass")] thanh_vien thanh_vien)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(thanh_vien).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(thanh_vien);
        //}

        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(thanh_vien_model model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Vui lòng kiểm tra lại các trường.");
                return View(model);
            }
            try
            {
                var _addNew = db.thanh_vien.Find(model.id);
                if (_addNew == null)
                {
                    return View(model);
                }
                _addNew.ho_ten = model.ho_ten ?? null;
                _addNew.dia_chi = model.dia_chi ?? null;
                _addNew.lon = model.lon ?? null;
                _addNew.lat = model.lat ?? null;
                _addNew.so_cmt = model.so_cmt ?? null;
                _addNew.nghe_nghiep = model.nghe_nghiep ?? null;
                _addNew.hoc_van = model.hoc_van ?? null;
                _addNew.hinh_anh = model.hinh_anh ?? null;
                _addNew.biet_danh = model.biet_danh ?? null;
                _addNew.gioi_tinh = model.gioi_tinh ?? null;
                string dateTime = model.ngay_sinh != null ? model.ngay_sinh : null;
                DateTime? dt = new DateTime();
                if (dateTime != null)
                {
                    dt = Convert.ToDateTime(dateTime);
                }
                _addNew.ngay_sinh = model.ngay_sinh != null ? dt : null;
                _addNew.ngay_tao = DateTime.Now;
                _addNew.cq_ctac = model.cq_ctac ?? null;
                _addNew.email = model.email ?? null;
                var passHash = model.pass != null ? configs.Encrypt(model.pass) : null;
                _addNew.pass = passHash;
                _addNew.trinh_do = model.trinh_do ?? null;
                _addNew.so_dien_thoai = model.so_dien_thoai ?? null;
                db.Entry(_addNew).State = EntityState.Modified;
                db.SaveChanges();
                // set cookie đăng nhập 

gpw/gpw/Views/ThanhVien/Delete.cshtml
@model gpw.Models.thanh_vien

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>thanh_vien</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ho_ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ho_ten)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dia_chi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dia_chi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.so_cmt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.so_cmt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nghe_nghiep)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nghe_nghiep)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hoc_van)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hoc_van)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hinh_anh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hinh_anh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.biet_danh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.biet_danh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.doi_thu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.doi_thu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gioi_tinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gioi_tinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ngay_sinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngay_sinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ngay_tao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngay_tao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.trang_thai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.trang_thai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.quyen_han)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quyen_han)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cq_ctac)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cq_ctac)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pass)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

gpw/gpw/Views/ThanhVien/Details.cshtml
@using gpw.helpers;
@model gpw.Models.thanh_vien

@{
    ViewBag.Title = "Trang cá nhân ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section meta {
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
}

@*@{
    if (configs.getCookie("ten_thanh_vien") != "")
    {
        ViewBag.Title += configs.getCookie("ten_thanh_vien");
    }
}*@


<div class="row section_1" style="background: #fff;">
    <div class="col-md-8">
        <div class="page-header">
            <h1>@ViewBag.Title</h1>
        </div>
        @if (configs.getCookie("thanhvien_id") != "")
        {
            <p>
                @Html.ActionLink("Sửa thông tin cá nhân", "Edit", new { id = Model.id }) | <a href="/ThanhVien/TaoGiaPha/@Model.id">Khai báo gia phả</a>
            </p>
        }
        
        @if (Model != null)
        {
            <div class="thumbnail">
                <img src="@Model.hinh_anh" alt="..." style="width: 100px; height: 125px;">
                <div class="caption">
                    <h3>Họ tên: @Model.ho_ten</h3>
                    <p>Nơi sống: @Model.dia_chi</p>
                    <p>Email: @Model.email</p>
                    <p>Số điện thoại: @Model.so_dien_thoai</p>
                    <p>Ngày sinh: @string.Format("{0:dd/MM/yyyy}", @Model.ngay_sinh)</p>
                </div>
            </div>
            
            { Html.RenderAction("LoadThanhVien", "ThanhVien", new { id = Model.id }); }
        }

    </div>
    <div class="col-md-4">
        @*<img src="~/images/caudoiphai.png" class="img-responsive" style="display: inline-block;" />
            <img src="~/images/caudoitrai.png" class="img-responsive" style="display: inline-block;" />*@
        <div class="panel panel-default box_giapha">
            <div class="panel-heading kf_heading_1" style="padding: 0;">
                <h3>Tìm kiếm</h3>
            </div>

            <div class="panel-body">
                @*@using (Html.BeginForm("Search", "Home", FormMethod.Post, htmlAttributes: new { @class = "form-inline", role = "form", @id = "form_search" }))
                    {
                        <div class="form-group">
                            <div class="input-group">
                                <input type="search" name="keyword" id="keyword" class="form-control" placeholder="Nhập địa chỉ email hoặc số điện thoại" required />
                            </div>
                        </div>
                        <button class="btn btn-primary"><i class="fa fa-search"></i> Tìm kiếm</button>
                    }*@
                <div class="search-bar">
                    <form action="/Home/Search" method="GET" role="form" id="form_search">
                        <div class="form-group">
                            <input style="max-width: 100%;" type="text" class="form-control" name="keyword" id="keyword" placeholder="Nhập từ khóa tìm kiếm">
                        </div>
                        <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                    </form>
                </div>
            </div>
        </div>

        <div class="panel panel-default box_giapha">
            <div class="panel-heading kf_heading_1" style="padding-bottom: 0;">
                <h3>Thống kê thành viên</h3>
            </div>
            <div class="panel-body">
                @*@{Html.RenderAction("DsUser");}*@
                <div class="col-md-12 item_thanhvien">
                    <h3>Thành viên già nhất:</h3>
                    <ul id="person_flat">
                        <li><a href="#">Dương Trung Hiếu</a> <i>Ngày sinh: 4/11/1960</i></li>
                    </ul>
                </div>
                <div class="col-md-12 item_thanhvien">
                    <h3>Thành viên trẻ nhất:</h3>
                    <ul id="person_flat">
                        <li><a href="#">Dương Viết Xuân</a> <i>Ngày sinh: 23/11/2000</i></li>
                    </ul>
                </div>
                <div class="col-md-12 item_thanhvien border_w0">
                    <h3>Thành viên mới nhất:</h3>
                    <ul id="person_flat">
                        <li><a href="#">Dương Thị Mùi</a>, </li>
                        <li><a href="#">Dương Văn Dần</a>, </li>
                        <li><a href="#">Dương Thúy Mùi</a>, </li>
                        <li><a href="#">Dương Văn Nhàn</a>, </li>
                        <li><a href="#">Dương Thúy Nhàn</a>,</li>
                        <li><span>...</span></li>
                        @*<li><a href="#"><img src="~/images/person-girl-flat.png" /></a></li>*@
                    </ul>
                </div>

                <a href="#" style="float: right;">Xem tất cả</a>
            </div>
        </div>

        <div class="panel panel-default box_giapha">
            <div class="panel-body">
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="height: 80px;">

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <p>Đừng so sánh mình với bất cứ ai trong thế giới này. Nếu bạn làm như vậy có nghĩa bạn đang sỉ nhục chính bản thân mình. </p>
                            <b style="float: right; margin-top: 5px;">Bill Gates</b>
                        </div>
                        <div class="item">
                            <p>Ta không được chọn nơi mình sinh ra. Nhưng ta được chọn cách mình sẽ sống.</p>
                            <b style="float: right; margin-top: 5px;">Khuyết danh</b>
                        </div>
                    </div>

                    <!-- Indicators -->
                    <ol class="carousel-indicators" style="bottom: 0;">
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active" style="background: #333;"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="1" style="background: #333;"></li>
                    </ol>
                </div>
            </div>

        </div>

    </div>
</div>


gpw/gpw/Views/ThanhVien/Login.cshtml
@using gpw.Models
@model thanh_vien_login_model
@{
    ViewBag.Title = "Thành viên đăng nhập";
}

@section meta {
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
}

<div class="row" style="background: #fff;">
    <div class="col-md-8" id="dang_nhap_thanh_vien_moi">
        <div class="page-header">
            <h2>@ViewBag.Title.</h2>
        </div>
        @using (Html.BeginForm("Login", "ThanhVien", FormMethod.Post, new { id = "form_dang_nhap_thanh_vien", role = "form" }))
        {
            <div class="form-horizontal">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Đăng nhập" class="btn btn-default" />
                    </div>
                </div>
                <p>
                    @Html.ActionLink("Đăng ký tài khoản thành viên", "Create")
                </p>
            </div>

        }
    </div>
    <div class="col-md-4">
        @*<img src="~/images/caudoiphai.png" class="img-responsive" style="display: inline-block;" />
            <img src="~/images/caudoitrai.png" class="img-responsive" style="display: inline-block;" />*@
        <div class="panel panel-default box_giapha">
            <div class="panel-heading kf_heading_1" style="padding: 0;">
                <h3>Tìm kiếm</h3>
            </div>

            <div class="panel-body">
                @*@using (Html.BeginForm("Search", "Home", FormMethod.Post, htmlAttributes: new { @class = "form-inline", role = "form", @id = "form_search" }))
                    {
                        <div class="form-group">
                            <div class="input-group">
                                <input type="search" name="keyword" id="keyword" class="form-control" placeholder="Nhập địa chỉ email hoặc số điện thoại" required />
                            </div>
                        </div>
                        <button class="btn btn-primary"><i class="fa fa-search"></i> Tìm kiếm</button>
                    }*@
                <div class="search-bar">
                    <form action="/Home/Search" method="GET" role="form" id="form_search">
                        <div class="form-group">
                            <input style="max-width: 100%;" type="text" class="form-control" name="keyword" id="keyword" placeholder="Nhập từ khóa tìm kiếm">
                        </div>
                        <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                    </form>
                </div>
            </div>
        </div>

        <div class="panel panel-default box_giapha">
            <div class="panel-heading kf_heading_1" style="padding-bottom: 0;">
                <h3>Thống kê thành viên</h3>
            </div>
            <div class="panel-body">
                @*@{Html.RenderAction("DsUser");}*@
                <div class="col-md-12 item_thanhvien">
                    <h3>Thành viên già nhất:</h3>
                    <ul id="person_flat">
                        <li><a href="#">Dương Trung Hiếu</a> <i>Ngày sinh: 4/11/1960</i></li>
                    </ul>
                </div>
                <div class="col-md-12 item_thanhvien">
                    <h3>Thành viên trẻ nhất:</h3>
                    <ul id="person_flat">
                        <li><a href="#">Dương Viết Xuân</a> <i>Ngày sinh: 23/11/2000</i></li>
                    </ul>
                </div>
                <div class="col-md-12 item_thanhvien border_w0">
                    <h3>Thành viên mới nhất:</h3>
                    <ul id="person_flat">
                        <li><a href="#">Dương Thị Mùi</a>, </li>
                        <li><a href="#">Dương Văn Dần</a>, </li>
                        <li><a href="#">Dương Thúy Mùi</a>, </li>
                        <li><a href="#">Dương Văn Nhàn</a>, </li>
                        <li><a href="#">Dương Thúy Nhàn</a>,</li>
                        <li><span>...</span></li>
                        @*<li><a href="#"><img src="~/images/person-girl-flat.png" /></a></li>*@
                    </ul>
                </div>

                <a href="#" style="float: right;">Xem tất cả</a>
            </div>
        </div>

        <div class="panel panel-default box_giapha">
            <div class="panel-body">
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="height: 80px;">

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <p>Đừng so sánh mình với bất cứ ai trong thế giới này. Nếu bạn làm như vậy có nghĩa bạn đang sỉ nhục chính bản thân mình. </p>
                            <b style="float: right; margin-top: 5px;">Bill Gates</b>
                        </div>
                        <div class="item">
                            <p>Ta không được chọn nơi mình sinh ra. Nhưng ta được chọn cách mình sẽ sống.</p>
                            <b style="float: right; margin-top: 5px;">Khuyết danh</b>
                        </div>
                    </div>

                    <!-- Indicators -->
                    <ol class="carousel-indicators" style="bottom: 0;">
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active" style="background: #333;"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="1" style="background: #333;"></li>
                    </ol>
                </div>
            </div>

        </div>

    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

gpw/gpw/Views/ThanhVien/_LoadThanhVien.cshtml
@model List<gpw.Models.quan_he_thanh_vien>

@if (Model != null)
{
    if (Model.Count > 0)
    {
        <h3>Danh sách thành viên: </h3>
    <ul>
        @foreach (var item in Model)
        {
            <li>
                @item.ten_quan_he - 
                @if (item.thanh_vien_qh_id != null)
                {
                    <a href="/ThanhVien/Details/@item.thanh_vien_qh_id">@item.ten_thanh_vien</a>
                }
                else
                {
                    <a href="#">@item.ten_thanh_vien</a>
                }
                - quê quán: @item.que_quan<span>.</span>
                @{Html.RenderAction("LoadThanhVienCungQH", "ThanhVien", new { tqh = @item.ten_quan_he, ttv = @item.ten_thanh_vien, id = item.thanh_vien_id });}
            </li>
        }
    </ul>
    }

}

gpw/gpw/Views/ThanhVien/_LoadThanhVienCungQH.cshtml
@model List<gpw.Models.quan_he_thanh_vien>

@if (Model != null)
{
    if (Model.Count > 0)
    {
        <div style="border: 1px solid #cbcbcb;padding: 10px;">
            <h3 style="font-size: 14px; margin-top: 0;">Danh sách thành viên cùng quan hệ: </h3>
            <ul style="list-style-type:none;">
                @foreach (var item in Model)
                {
                    <li style="display: inline-block;">
                        @if (item.thanh_vien_qh_id != null)
                        {
                            <a href="/ThanhVien/Details/@item.thanh_vien_qh_id">@item.ten_thanh_vien</a><span>, </span>
                        }
                        else
                        {
                            <a href="#">@item.ten_thanh_vien</a><span>, </span>
                        }
                    </li>
                }
            </ul>
        </div>
    }

}